# Generated by Django 5.2.9 on 2026-02-07 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0006_alter_apikey_environment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user.login", "User Login"),
                            ("user.logout", "User Logout"),
                            ("user.register", "User Registration"),
                            ("login.failed", "Login Failed"),
                            ("password.reset.request", "Password Reset Requested"),
                            ("password.reset.complete", "Password Reset Completed"),
                            ("password.changed", "Password Changed"),
                            ("email.verified", "Email Verified"),
                            ("email.verification.sent", "Verification Email Sent"),
                            ("email.verification.Failed", "Verification Email Failed"),
                            ("social.login", "Social Login"),
                            ("social.connected", "Social Account Connected"),
                            ("social.disconnected", "Social Account disconnected"),
                            ("api_key.created", "API Key Created"),
                            ("api_key.revoked", "API Key Revoked"),
                            ("api_key.used", "API Key Used"),
                            ("user.created", "User Created"),
                            ("user.updated", "User Updated"),
                            ("user.deleted", "User Deleted"),
                            ("user.role.changed", "User Role Changed"),
                            ("org.created", "Organization Created"),
                            ("org.updated", "Organization Updated"),
                            ("org.member.added", "Member Added to Organization"),
                            ("org.member.removed", "Member Removed from Organization"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event context"
                    ),
                ),
                ("target_object_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "success",
                    models.BooleanField(
                        default=False, help_text="Whether the action succeeded"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if action failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_api_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="API Key used for this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="organizations.apikey",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs_as_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "event_type"],
                        name="audit_logs_created_7fea1d_idx",
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_logs_organiz_86ff70_idx",
                    ),
                    models.Index(
                        fields=["actor_user", "-created_at"],
                        name="audit_logs_actor_u_96cae6_idx",
                    ),
                ],
            },
        ),
    ]
