# Generated by Django 5.2.9 on 2026-02-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("user.login", "User Login"),
                    ("user.logout", "User Logout"),
                    ("user.register", "User Registration"),
                    ("login.failed", "Login Failed"),
                    ("password.reset.request", "Password Reset Requested"),
                    ("password.reset.complete", "Password Reset Completed"),
                    ("password.changed", "Password Changed"),
                    ("email.verified", "Email Verified"),
                    ("email.verification.sent", "Verification Email Sent"),
                    ("email.verification.failed", "Verification Email Failed"),
                    ("social.login", "Social Login"),
                    ("social.connected", "Social Account Connected"),
                    ("social.disconnected", "Social Account disconnected"),
                    ("api_key.created", "API Key Created"),
                    ("api_key.revoked", "API Key Revoked"),
                    ("api_key.used", "API Key Used"),
                    ("user.created", "User Created"),
                    ("user.updated", "User Updated"),
                    ("user.deleted", "User Deleted"),
                    ("user.role.changed", "User Role Changed"),
                    ("org.created", "Organization Created"),
                    ("org.updated", "Organization Updated"),
                    ("org.member.added", "Member Added to Organization"),
                    ("org.member.removed", "Member Removed from Organization"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="success",
            field=models.BooleanField(
                default=True, help_text="Whether the action succeeded"
            ),
        ),
    ]
