# Generated by Django 5.2.9 on 2026-03-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_auditlog_event_type'),
        ('organizations', '0013_project_apikey_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.project'),
        ),
    ]
