# Generated by Django 5.2.9 on 2026-04-19 11:12

from django.db import migrations


def drop_unique_verified_email_constraint(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE account_emailaddress DROP CONSTRAINT IF EXISTS unique_verified_email;"
        )
        return

    if vendor == "sqlite":
        schema_editor.execute("DROP INDEX IF EXISTS unique_verified_email;")


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_emailaddress_drop_unique_email"),
        ("authentication", "0005_alter_auditlog_event_type"),
    ]

    operations = [
        migrations.RunPython(
            drop_unique_verified_email_constraint,
            migrations.RunPython.noop,
        ),
    ]
