# Generated by Django 5.2.9 on 2026-04-20

from django.db import migrations


def drop_unique_verified_email_index(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE account_emailaddress DROP CONSTRAINT IF EXISTS unique_verified_email;"
        )
        schema_editor.execute("DROP INDEX IF EXISTS unique_verified_email;")
        return

    if vendor == "sqlite":
        schema_editor.execute("DROP INDEX IF EXISTS unique_verified_email;")


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_emailaddress_unique_primary_email"),
        ("authentication", "0006_drop_account_unique_verified_email"),
    ]

    operations = [
        migrations.RunPython(
            drop_unique_verified_email_index,
            migrations.RunPython.noop,
        ),
    ]
