"""
Django settings for hvt project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from corsheaders.defaults import default_headers
from urllib.parse import urlparse

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: str = ""):
    raw_value = os.getenv(name, default)
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _host_from_url(value: str) -> str:
    if not value:
        return ""
    parsed = urlparse(value)
    return (parsed.hostname or "").strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "").strip()
if DEBUG:
    SECRET_KEY = SECRET_KEY or "django-insecure-q=rdhtslcm#@a7pm-k2u5(67+++14#(#ez*at@&-!d*h@k#)m+"
elif not SECRET_KEY or SECRET_KEY.startswith("django-insecure-") or SECRET_KEY == "change-me-in-production":
    raise ImproperlyConfigured("SECRET_KEY must be set to a strong value when DEBUG is false.")

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173").rstrip("/")
RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()
RAILWAY_PUBLIC_HOST = _host_from_url(RAILWAY_PUBLIC_DOMAIN) or RAILWAY_PUBLIC_DOMAIN

ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS",
    ",".join(
        [
            host
            for host in [
                "localhost",
                "127.0.0.1",
                "testserver",
            ]
        ]
    )
    if DEBUG
    else ",".join(
        [
            host
            for host in [
                RAILWAY_PUBLIC_HOST,
                "healthcheck.railway.app",
            ]
            if host
        ]
    ),
)
for extra_host in [RAILWAY_PUBLIC_HOST, "healthcheck.railway.app"]:
    if extra_host and extra_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(extra_host)
configured_public_hosts = [host for host in ALLOWED_HOSTS if host != "healthcheck.railway.app"]
if not DEBUG and not configured_public_hosts:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be configured when DEBUG is false.")

default_frontend_origins = []
if DEBUG:
    default_frontend_origins.extend(["http://localhost:3000", "http://localhost:5173"])
if FRONTEND_URL:
    default_frontend_origins.append(FRONTEND_URL)
default_frontend_origins = list(dict.fromkeys(default_frontend_origins))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "corsheaders",
    # Third-Party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "drf_spectacular",
    "django_filters",
    # Local apps
    "hvt.apps.authentication",
    "hvt.apps.organizations",
    "hvt.apps.users",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "hvt.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "hvt" / "apps" / "authentication" / "templates",
            BASE_DIR / "hvt" / "apps" / "organizations" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hvt.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Supports DATABASE_URL (production/Docker) with fallback to individual env vars (local dev)

DATABASES = {
    "default": dj_database_url.config(
        default=(
            f"postgres://{os.getenv('DB_USER', '')}:{os.getenv('DB_PASSWORD', '')}"
            f"@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}"
            f"/{os.getenv('DB_NAME', '')}"
        ),
        conn_max_age=600,
    )
}

if not DEBUG and _env_bool("DATABASE_SSL_REQUIRE", False):
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"]["sslmode"] = "require"

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    ",".join(default_frontend_origins),
)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    
CORS_ALLOW_CREDENTIALS = True

# Preserve django-cors-headers defaults and allow runtime API-key auth from browsers.
CORS_ALLOW_HEADERS = [*default_headers, "x-api-key"]

CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    ",".join(CORS_ALLOWED_ORIGINS),
)
if not DEBUG and not CORS_ALLOWED_ORIGINS:
    raise ImproperlyConfigured(
        "CORS_ALLOWED_ORIGINS must be configured when DEBUG is false."
    )

USE_X_FORWARDED_HOST = _env_bool("USE_X_FORWARDED_HOST", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_REDIRECT_EXEMPT = _env_list(
    "SECURE_REDIRECT_EXEMPT",
    "healthz/,readyz/" if not DEBUG else "",
)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(
    os.getenv("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG
)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv(
    "SECURE_REFERRER_POLICY",
    "strict-origin-when-cross-origin" if not DEBUG else "same-origin",
)
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")
EXPOSE_ADMIN = _env_bool("EXPOSE_ADMIN", DEBUG)
EXPOSE_API_DOCS = _env_bool("EXPOSE_API_DOCS", DEBUG)
# Custom User model
AUTH_USER_MODEL = "users.User"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# Ensure headless mode is enabled for django-allauth
HEADLESS_ONLY = True

# Define where the email links should point to on your frontend
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_URL}/auth/verify-email/{{key}}",
    "account_reset_password_from_key": f"{FRONTEND_URL}/auth/password-reset/{{key}}",
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 1

REDIS_URL = os.getenv("REDIS_URL", "").strip()
USE_REDIS_CACHE = _env_bool("USE_REDIS_CACHE", False)
if USE_REDIS_CACHE:
    if not REDIS_URL:
        raise ImproperlyConfigured(
            "REDIS_URL must be configured when USE_REDIS_CACHE is enabled."
        )
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "hvt-local-cache",
        }
    }

# Django Rest Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "hvt.apps.authentication.backends.HVTJWTCookieAuthentication",
        "hvt.apps.authentication.backends.HVTJWTAuthentication",
        "hvt.apps.authentication.backends.APIKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "hvt.apps.authentication.throttling.BurstRateThrottle",
        "hvt.apps.authentication.throttling.OrganizationRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "burst": "20/second",
        "organization": "1000/hour",
        "api_key": "100/minute",
        "anon": "10/min",
        "auth_login_ip": "10/min",
        "auth_login_email": "10/hour",
        "auth_register_ip": "5/hour",
        "auth_register_email": "3/hour",
        "auth_runtime_register_api_key": "20/hour",
        "auth_runtime_password_reset_api_key": "10/hour",
        "auth_password_reset_ip": "5/hour",
        "auth_password_reset_email": "3/hour",
        "auth_password_reset_confirm_ip": "10/hour",
        "auth_password_reset_validate_ip": "30/hour",
        "auth_password_change_user": "10/hour",
        "auth_email_verification_ip": "10/hour",
        "auth_resend_verification_ip": "5/hour",
        "auth_resend_verification_email": "3/hour",
        "auth_runtime_resend_verification_api_key": "10/hour",
        "auth_social_login_ip": "10/min",
        "auth_runtime_login_api_key": "60/min",
        "auth_runtime_social_api_key": "60/min",
        "auth_token_refresh": "60/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Standardized error envelope for all API errors
    "EXCEPTION_HANDLER": "hvt.exceptions.hvt_exception_handler",
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "hvt.pagination.StandardPagination",
    "PAGE_SIZE": 25,
    # Filtering
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# drf-spectacular (OpenAPI / Swagger)
SPECTACULAR_SETTINGS = {
    "TITLE": "HVT Authentication API",
    "DESCRIPTION": (
        "HVT is a REST-first authentication service that serves as an identity provider "
        "and single source of truth for authentication. It handles user lifecycle management, "
        "JWT + refresh token auth, social OAuth (Google/GitHub), per-org API keys, "
        "role-based access control, webhooks, and audit logging."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "TAGS": [
        {"name": "Auth", "description": "Login, registration, password reset, social OAuth, and token management"},
        {"name": "Users", "description": "User CRUD, role management, and organization membership"},
        {"name": "Organizations", "description": "Organization lifecycle and configuration"},
        {"name": "API Keys", "description": "Create, list, and revoke API keys for server-to-server auth"},
        {"name": "Webhooks", "description": "Configure webhooks for auth event notifications"},
    ],
    "ENUM_NAME_OVERRIDES": {
        "UserRoleEnum": "hvt.apps.users.models.User.Role",
        "InvitationRoleEnum": "hvt.apps.organizations.models.OrganizationInvitation.Role",
    },
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": False,
        "filter": True,
    },
    "FIELD_TYPE_MAPPING": {
        "rest_framework.fields.ReadOnlyField": "str",
    }
}

# Simple JWT
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "TOKEN_OBTAIN_SERIALIZER": "hvt.apps.authentication.tokens.HVTTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "hvt.apps.authentication.tokens.HVTTokenRefreshSerializer",
}

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True

# dj-rest-auth

# Cookie defaults that work for cross-origin frontends in production while still
# keeping local http development simple.
jwt_cookie_secure_default = not DEBUG
jwt_cookie_samesite_default = "None" if jwt_cookie_secure_default else "Lax"

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "auth-token",
    "JWT_AUTH_REFRESH_COOKIE": "refresh-token",
    # Frontends on another origin must use credentialed requests and require
    # SameSite=None; Secure cookies for browser XHR/fetch to include them.
    "JWT_AUTH_HTTPONLY": True,
    "JWT_AUTH_SAMESITE": os.getenv("JWT_AUTH_SAMESITE", jwt_cookie_samesite_default),
    "JWT_AUTH_SECURE": os.getenv("JWT_AUTH_SECURE", str(jwt_cookie_secure_default)).lower() == "true",
    "TOKEN_MODEL": None,
    "REGISTER_SERIALIZER": "hvt.api.v1.serializers.users.ControlPlaneRegisterSerializer",
    "LOGIN_SERIALIZER": "hvt.api.v1.serializers.users.CustomLoginSerializer",
    "SOCIAL_LOGIN_SERIALIZER": "hvt.api.v1.serializers.users.CustomSocialLoginSerializer",
    "JWT_TOKEN_CLAIMS_SERIALIZER": "hvt.apps.authentication.tokens.HVTTokenObtainPairSerializer",
    "PASSWORD_RESET_SERIALIZER": "hvt.apps.authentication.serializers.HVTPasswordResetSerializer",
    "PASSWORD_RESET_USE_SITES_DOMAIN": False,
}

# dj-rest-auth 7.0.1 still reads several legacy top-level settings from its
# cookie auth code paths. Mirror the REST_AUTH values here so login, /me, and
# refresh all resolve the same cookie names and flags.
REST_USE_JWT = REST_AUTH["USE_JWT"]
JWT_AUTH_COOKIE = REST_AUTH["JWT_AUTH_COOKIE"]
JWT_AUTH_REFRESH_COOKIE = REST_AUTH["JWT_AUTH_REFRESH_COOKIE"]
JWT_AUTH_HTTPONLY = REST_AUTH["JWT_AUTH_HTTPONLY"]
JWT_AUTH_SECURE = REST_AUTH["JWT_AUTH_SECURE"]
JWT_AUTH_SAMESITE = REST_AUTH["JWT_AUTH_SAMESITE"]
JWT_TOKEN_CLAIMS_SERIALIZER = REST_AUTH["JWT_TOKEN_CLAIMS_SERIALIZER"]
EMAIL_BACKEND = "hvt.apps.authentication.email.ResendEmailBackend"

PASSWORD_RESET_CONFIRM_URL = "password/reset/confirm/{uid}/{token}"
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# SOCIAL AUTHENTICATION(Google & Github)
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Custom adapter for email-only users
SOCIALACCOUNT_ADAPTER = "hvt.apps.authentication.adapters.CustomSocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
        },
    },
    "github": {
        "SCOPE": ["user:email"],
        "APP": {
            "client_id": os.getenv("GITHUB_CLIENT_ID", ""),
            "secret": os.getenv("GITHUB_CLIENT_SECRET", ""),
        },
    },
}

RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_WEBHOOK_SIGNING_KEY = os.getenv("RESEND_WEBHOOK_SIGNING_KEY", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@hvt.dev")

# allauth - Use the custom adapter to point links to the frontend
ACCOUNT_ADAPTER = "hvt.apps.authentication.adapters.ResendAccountAdapter"

# LOGGING Configuration
APP_LOG_LEVEL = "INFO" if DEBUG else "WARNING"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "hvt.apps.authentication": {
            "handlers": ["console"],
            "level": APP_LOG_LEVEL,
            "propagate": True,
        },
        "hvt.apps.users": {
            "handlers": ["console"],
            "level": APP_LOG_LEVEL,
            "propagate": True,
        },
    },
}
