server {
    listen 80;
    server_name api.hvts.app;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /home/hvt/hvt/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/hvt/hvt/hvt-gunicorn.sock;
    }
}