# Generated by Django 5.2.9 on 2026-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_test",
            field=models.BooleanField(
                default=False, help_text="Test user are only access via test API keys"
            ),
        ),
    ]
