# Generated by Django 5.2.9 on 2026-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0020_project_allowed_origins'),
        ('users', '0005_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'project'), name='uniq_user_email_per_project'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('email',), name='uniq_user_email_when_project_null'),
        ),
    ]
