# Generated by Django 5.2.9 on 2026-01-06 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apikey",
            old_name="scope",
            new_name="scopes",
        ),
    ]
