# Generated by Django 5.2.9 on 2026-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_rename_scope_apikey_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="environment",
            field=models.CharField(
                choices=[("test", "Test"), ("live", "Live")],
                default="test",
                help_text="Test keys only test data, live keys access production data",
                max_length=4,
            ),
        ),
    ]
