# Generated by Django 5.2.9 on 2026-01-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_apikey_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="environment",
            field=models.CharField(
                choices=[("test", "Test"), ("live", "Live")],
                default="test",
                help_text="Test keys only access test data, live keys access production data",
                max_length=4,
            ),
        ),
    ]
