# Generated by Django 5.2.9 on 2026-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_webhook_webhookdelivery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookdelivery",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="webhook",
            old_name="decription",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="webhook",
            old_name="faliure_count",
            new_name="failure_count",
        ),
        migrations.RenameField(
            model_name="webhookdelivery",
            old_name="event_types",
            new_name="event_type",
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["webhook", "-created_at"], name="webhook_del_webhook_b549ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_retry_at"], name="webhook_del_status_741062_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="webhookdelivery",
            table="webhook_deliveries",
        ),
    ]
