# Generated by Django 5.2.9 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_alter_webhookdelivery_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="environment",
            field=models.CharField(
                choices=[("test", "Test"), ("live", "Live")],
                default="live",
                help_text="Test keys only access test data, live keys access production data",
                max_length=4,
            ),
        ),
    ]
