# Generated by Django 5.2.9 on 2026-02-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_revert_apikey_environment_default_to_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="consecutive_failures",
            field=models.IntegerField(
                default=0,
                help_text="Consecutive failed deliveries. Webhook auto-disables at 10.",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="request_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="request_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="response_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
