# Generated by Django 5.2.9 on 2026-03-22 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_default_projects_and_backfill_keys(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Project = apps.get_model("organizations", "Project")
    APIKey = apps.get_model("organizations", "APIKey")

    for organization in Organization.objects.all().iterator():
        project, _ = Project.objects.get_or_create(
            organization=organization,
            is_default=True,
            defaults={
                "name": "Default",
                "slug": "default",
                "allow_signup": organization.allow_signup,
                "is_active": True,
            },
        )
        APIKey.objects.filter(
            organization=organization,
            project__isnull=True,
        ).update(project=project)


def reverse_default_projects_and_backfill_keys(apps, schema_editor):
    APIKey = apps.get_model("organizations", "APIKey")
    APIKey.objects.update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=225)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_signup', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['created_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.project'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_project_slug_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='uniq_default_project_per_organization'),
        ),
        migrations.RunPython(
            create_default_projects_and_backfill_keys,
            reverse_default_projects_and_backfill_keys,
        ),
    ]
