# Generated by Django 5.2.9 on 2026-03-22 20:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_project_apikey_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=32)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uris', models.JSONField(blank=True, default=list, help_text='Allowed frontend callback URLs for this provider config.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_provider_configs', to='organizations.project')),
            ],
            options={
                'db_table': 'social_provider_configs',
                'ordering': ['provider', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'provider'), name='uniq_social_provider_per_project')],
            },
        ),
    ]
