# Generated by Django 5.2.9 on 2026-03-23 00:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_webhook_projects(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Project = apps.get_model("organizations", "Project")
    Webhook = apps.get_model("organizations", "Webhook")

    for organization in Organization.objects.all().iterator():
        project, _ = Project.objects.get_or_create(
            organization=organization,
            is_default=True,
            defaults={
                "name": "Default",
                "slug": "default",
                "allow_signup": organization.allow_signup,
            },
        )
        Webhook.objects.filter(
            organization=organization,
            project__isnull=True,
        ).update(project=project)


def clear_webhook_projects(apps, schema_editor):
    Webhook = apps.get_model("organizations", "Webhook")
    Webhook.objects.update(project=None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("organizations", "0014_socialproviderconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="organizations.project",
            ),
        ),
        migrations.RunPython(backfill_webhook_projects, clear_webhook_projects),
        migrations.AlterField(
            model_name="webhook",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="organizations.project",
            ),
        ),
    ]
