# Generated by Django 5.2.9 on 2026-04-07 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_webhook_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text='Stable permission identifier such as orders.read.own.', max_length=100, validators=[django.core.validators.RegexValidator(message="Use lowercase letters, numbers, and separators like '.', '_', ':', or '-'.", regex='^[a-z0-9]+(?:[._:-][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='organizations.project')),
            ],
            options={
                'db_table': 'project_permissions',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text='Stable role identifier such as buyer or teacher.', max_length=100, validators=[django.core.validators.RegexValidator(message="Use lowercase letters, numbers, and separators like '.', '_', ':', or '-'.", regex='^[a-z0-9]+(?:[._:-][a-z0-9]+)*$')])),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_default_signup', models.BooleanField(default=False, help_text='Assign this role automatically during public runtime signup.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_roles', to='organizations.project')),
            ],
            options={
                'db_table': 'project_roles',
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='organizations.projectpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='organizations.projectrole')),
            ],
            options={
                'db_table': 'project_role_permissions',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='organizations.ProjectRolePermission', to='organizations.projectpermission'),
        ),
        migrations.CreateModel(
            name='UserProjectRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organizations.projectrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_project_roles',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectpermission',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uniq_project_permission_slug'),
        ),
        migrations.AddConstraint(
            model_name='projectrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_project_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uniq_project_role_slug'),
        ),
        migrations.AddConstraint(
            model_name='userprojectrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_project_role_assignment'),
        ),
    ]
