# Generated by Django 5.2.9 on 2026-04-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_projectpermission_projectrole_projectrolepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='app_roles',
            field=models.ManyToManyField(blank=True, related_name='organization_invitations', to='organizations.projectrole'),
        ),
        migrations.AddField(
            model_name='organizationinvitation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_invitations', to='organizations.project'),
        ),
    ]
