# Generated by Django 5.2.9 on 2026-04-22 08:12

import django.db.models.deletion
import hvt.apps.organizations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_project_allowed_origins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='is_self_assignable',
            field=models.BooleanField(default=False, help_text='Allow runtime users to request this role during registration.'),
        ),
        migrations.CreateModel(
            name='RuntimeInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role_slugs', models.JSONField(blank=True, default=list)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(default=hvt.apps.organizations.models._runtime_invitation_default_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_runtime_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_invitations', to='organizations.project')),
            ],
            options={
                'db_table': 'runtime_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'email'], name='runtime_inv_project_44d4d3_idx'), models.Index(fields=['project', 'status', '-created_at'], name='runtime_inv_project_22368d_idx')],
            },
        ),
    ]
